# Generated by Django 4.2 on 2026-02-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='session_mgmt_idx',
            old_name='session_user_mgmt_idx',
        ),
    ]
